apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: mandatkollen-gateway-class
spec:
  controllerName: k8s-gateway-nginx/nginx-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mandatkollen-gateway
  namespace: mandatkollen
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    external-dns.alpha.kubernetes.io/hostname: mandatkollen.se.
spec:
  gatewayClassName: mandatkollen-gateway-class
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: "*.mandatkollen.se"
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "*.mandatkollen.se"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: mandatkollen-prod-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mandatkollen-route
  namespace: mandatkollen
spec:
  parentRefs:
    - name: mandatkollen-gateway
      sectionName: https
  hostnames:
    - mandatkollen.se
    - www.mandatkollen.se
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mandatkollen
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mandatkollen-tls-redirect
  namespace: mandatkollen
spec:
  parentRefs:
    - name: mandatkollen-gateway
      sectionName: http
  hostnames:
    - mandatkollen.se
    - www.mandatkollen.se
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 443